language: java
sudo: false
cache:
  directories:
  - $HOME/.m2/repository
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script:
- jdk_switcher use oraclejdk8
- mvn test
- jdk_switcher use oraclejdk7
- mvn test
- bin/build-release.sh
matrix:
  fast_finish: true
  include:
  - env: STORM_RELEASE="0.10.0" MESOS_RELEASE="0.28.0"
  - env: STORM_RELEASE="0.10.0" MESOS_RELEASE="0.27.2"
  - env: STORM_RELEASE="0.9.6" MESOS_RELEASE="0.28.0"
  - env: STORM_RELEASE="0.9.6" MESOS_RELEASE="0.27.2"
# Deploy archives to GitHub release tags
deploy:
  provider: releases
  api_key:
    secure: SEKAUlMBRXrm9EY8JUYKrXQYC7v1+nJ2/0H23KvcZGbvBL6tMaY1jPJZ8vlCJjCwd69WUCc9a1p/IzYMkt6jz4xx2vB13MYL7GnQgltzEwCAVl7I6uw1r08SDyNdeCeBqZFTcPXmrWM5ByQ0q/4SqEqLMw1uCTfOQV1/XQeivkA=
  file: "storm-mesos-$(grep -1 -A 0 -B 0 '<version>' pom.xml | head -n 1 | awk '{print $1}' | sed -e 's/.*<version>//' | sed -e 's|</version>.*||')-storm$STORM_RELEASE-mesos$MESOS_RELEASE.tgz"
  skip_cleanup: true
  on:
    tags: true
    repo: mesos/storm
